chore: fix ts error by !!-ing find()'s callback return value
it failed with:
```
error TS2322: Type 'boolean | undefined' is not assignable to type
  'boolean'
```

probably didn't happen before due to typescript pkg update.